import pytest

MINIMAL_APT_DAT = """\
I
1100 Generated by WorldEditor

1 0 0 0 LEBL Test Airport
1302 datum_type AIRAC
100 45.00 1 0 0.25 1 3 1 09L 41.2800 2.0700 0 0 0 0 0 0 27R 41.2900 2.0900 0 0 0 0 0 0
19 41.2850 2.0750 1 Test Windsock
20 41.2860 2.0760 180.0 0 1 {A-1}
1300 41.2870 2.0770 90.0 gate props Gate 1
1301 A airline_ops AA BB
130 Test Boundary
111 41.2750 2.0650
111 41.2950 2.0650
111 41.2950 2.0850
113 41.2750 2.0850
110 1 0.25 0.0 Test Pavement
111 41.2800 2.0700 0 0
111 41.2900 2.0700 0 0
111 41.2900 2.0800 0 0
113 41.2800 2.0800 0 0
120 Test Linear Feature
111 41.2800 2.0700 1 0
115 41.2900 2.0800 1 0
99
"""


@pytest.fixture
def apt_dat():
    from xplane_airports.AptDat import AptDat
    return AptDat.from_file_text(MINIMAL_APT_DAT, "test.dat")


@pytest.fixture
def airport(apt_dat):
    return apt_dat.search_by_id("LEBL")


@pytest.fixture
def parsed_airport(airport):
    from xplane_apt_convert import ParsedAirport
    return ParsedAirport(airport)
