import pytest
from typer.testing import CliRunner

from xplane_apt_convert.cli import app

runner = CliRunner()

MINIMAL_DAT = """\
I
1100 Generated by WorldEditor

1 0 0 0 LEBL Test Airport
100 45.00 1 0 0.25 1 3 1 09L 41.2800 2.0700 0 0 0 0 0 0 27R 41.2900 2.0900 0 0 0 0 0 0
19 41.2850 2.0750 1 Test Windsock
99
"""


@pytest.fixture
def dat_file(tmp_path):
    p = tmp_path / "test.dat"
    p.write_text(MINIMAL_DAT)
    return p


class TestCLI:
    def test_help(self):
        result = runner.invoke(app, ["--help"])
        assert result.exit_code == 0
        assert "airport-ids" in result.output

    def test_local_file_geojson(self, dat_file, tmp_path):
        out = tmp_path / "out"
        result = runner.invoke(app, [
            "-a", "LEBL", "-i", str(dat_file), "-o", str(out), "-d", "GeoJSON", "-f", "runways",
        ])
        assert result.exit_code == 0
        assert (out / "LEBL.runways.geojson").exists()

    def test_feature_subset(self, dat_file, tmp_path):
        out = tmp_path / "out"
        runner.invoke(app, [
            "-a", "LEBL", "-i", str(dat_file), "-o", str(out), "-d", "GeoJSON", "-f", "runways",
        ])
        assert not (out / "LEBL.windsocks.geojson").exists()

    def test_both_input_options_raises(self, dat_file, tmp_path):
        result = runner.invoke(app, [
            "-a", "LEBL", "-i", str(dat_file), "-g", "-o", str(tmp_path),
        ])
        assert result.exit_code != 0

    def test_no_input_raises(self, tmp_path):
        result = runner.invoke(app, ["-a", "LEBL", "-o", str(tmp_path)])
        assert result.exit_code != 0

    def test_airport_not_found_aborts(self, dat_file, tmp_path):
        result = runner.invoke(app, [
            "-a", "XXXX", "-i", str(dat_file), "-o", str(tmp_path),
        ])
        assert result.exit_code != 0
